rust-minidump/rust-minidump

src/minidump_format.rs
This is a quick hack to ensure rust-minidump builds correctly under Windows. It's not pretty since minidump_format.rs is generated but it works. Let me know if you think there's a better approach to tackle the issue with type sizes across different architectures.
=> Fix building on Windows

minidump-common/src/format.rs, src/context.rs
This series gets me to the point where I can `minidump_stackwalk` and have at least the crashing thread line up with what crash-stats tells me.  I have an in-progress frame pointer unwind for aarch64, but that's not lining up with what crash-stats says, so we'll leave that bit for later.
=> add aarch64 support

minidump-common/src/format.rs, src/context.rs, src/system_info.rs
Turns out these are necessary to get reasonable things to happen for Android minidumps.
=> handle "old" aarch64 exception contexts

minidump-tools/src/lib.rs
The current implementation disassembles the entire memory region
containing the crashing ip.  But the entire region might not be
disassemblable (sp?): the region might start in the middle of a variable
length instruction or might contain just plain garbage in the case of
fixed width instructions.  And the underlying disassembler seems to give
up entirely in the case of stuff it can't disassemble, rather than
trying to move on.
Instead, let's start disassembling from the byte indicated by the
crashing ip.  This will at least produce reasonable output until we can
change the underlying disassembler or correctly call into the
disassembler to make it continue in the presence of garbage.
=> change get-minidump-instructions to disassemble from crashing ip

breakpad-symbols/src/lib.rs, breakpad-symbols/src/sym_file/mod.rs, minidump-processor/src/dwarf_symbolizer.rs, minidump-processor/src/processor.rs, minidump-tools/src/lib.rs, src/minidump.rs
There are still a bunch of warnings about doc comments and macros, but these warnings, at least, were easy to fix.
=> fix `dyn Trait` warnings

minidump-common/src/format.rs
This is a quick workaround to fix compilation on Rust 1.47.0, which was released to the stable channel today. It seems that custom derives no longer resolve the syntax tree correctly when declared in a macro that uses `ty` matchers. When updated to `tt`, it works however.
I yet have to pin it down and then potentially report this upstream.
Fixes https://github.com/luser/rust-minidump/issues/100
=> Change multi_structs macro to compile on 1.47.0

src/lib.rs
This is a public field on the Minidump struct, but the API currently
forces you to explicitly pull in scroll to use it.  It seems
reasonable for the crate to export the types which which is uses in
public APIs.
=> Re-export scroll::Endian

breakpad-symbols/Cargo.toml, breakpad-symbols/src/lib.rs, minidump-tools/Cargo.toml, minidump-tools/src/lib.rs
https://github.com/luser/rust-minidump/pull/97 updated the reqwest
version which by default uses async code now.  Migrate to the blocking
client feature instead.
=> Fixes for new reqwest version

.github/workflows/ci.yml, Cargo.toml, breakpad-symbols/src/lib.rs, breakpad-symbols/src/sym_file/mod.rs, breakpad-symbols/src/sym_file/parser.rs, examples/dumpmodules.rs, minidump-processor/src/bin/minidump_stackwalk.rs, minidump-processor/src/process_state.rs, minidump-processor/src/processor.rs, minidump-processor/src/stackwalker/mod.rs, minidump-processor/src/stackwalker/x86.rs, minidump-processor/src/stackwalker/x86_unittest.rs, minidump-processor/tests/test_processor.rs, minidump-tools/src/lib.rs, src/bin/minidump_dump.rs, src/context.rs, src/minidump.rs, src/synth_minidump.rs, tests/test_minidump.rs
Clippy tricked me into thinking there wouldn't be much it complained about... but that was a lie.
Most of this is boring but nice to get clippy's consistency I guess.  A few things stand out though:
* I added a few `Default` impls because clippy wanted those.  That's a public API addition so perhaps deserves some more careful consideration.  We could disable these warnings if better for now.  Though if `::new()` were to change on these it would also be a public API change so perhaps than no longer being able to use `Default` or it having different semantics at that point is fine.
* I added a few `allow(clippy::should_implement_trait)` attributes, clippy complains that those methods have expectations in common traits (`std::ops::Add` in this case) and should either impl that trait or use …
=> Enable all CI

.github/workflows/ci.yml
The intra-doc linking now works on rust stable.  No need to use
nightly anymore.
Also update caching action which is simpler to use in more recent
versions.
=> Use stable rustc for docs CI

breakpad-symbols/src/lib.rs, minidump-processor/src/processor.rs
The culprit of this lies in https://github.com/rust-lang/cargo/pull/8954, and some of my thoughts are summarized in https://github.com/rust-lang/cargo/pull/8954#issuecomment-747426703.
The workaround is to set the CWD explicitly.
Fixes #121 
cc @Swatinem 👋
=> Fix doctests on nightly by setting cwd explicitly

Cargo.toml, breakpad-symbols/Cargo.toml, breakpad-symbols/src/lib.rs, breakpad-symbols/src/sym_file/mod.rs, breakpad-symbols/src/sym_file/parser.rs, minidump-common/Cargo.toml, minidump-common/src/format.rs, minidump-common/src/lib.rs, minidump-common/src/traits.rs, minidump-processor/Cargo.toml, minidump-processor/src/dwarf_symbolizer.rs, minidump-processor/src/lib.rs, minidump-processor/src/process_state.rs, minidump-processor/src/processor.rs, minidump-processor/src/stackwalker/mod.rs, minidump-processor/src/stackwalker/unwind.rs, minidump-processor/src/stackwalker/x86.rs, minidump-processor/src/stackwalker/x86_unittest.rs, minidump-tools/Cargo.toml, minidump-tools/src/lib.rs, src/context.rs, src/lib.rs, src/minidump.rs
As you seem to be happy updating the code, I've adopted this to the 2018 edition.  Other than the strictly required `cargo fix --edition` this also replaces the `extern crate` statements with explicit `use` statements.
I realise this is a bit of a gratuitous change, so I won't mind at all if you'd rather not update the edition.
=> Update to 2018 edition

README.md, examples/dumpmodules.rs, minidump-processor/src/bin/minidump_stackwalk.rs, minidump-processor/src/processor.rs, minidump-processor/tests/test_processor.rs, minidump-tools/src/bin/dumpstack.rs, minidump-tools/src/bin/get-minidump-instructions.rs, src/bin/minidump_dump.rs, src/minidump.rs, src/system_info.rs, tests/test_minidump.rs
This is a follow-up to #109, applying `cargo fix --edition-idioms` and removing all `extern crate` declarations.
cc @flub
=> Fix Rust Edition 2018 idioms

minidump-common/src/format.rs, src/minidump.rs, src/synth_minidump.rs, tests/test_minidump.rs
The CrashpadInfo stream is an extension containing additional annotations for
the minidump and its modules.
=> Implement CrashpadInfo stream

src/synth_minidump.rs
Follow-up to #119 adding a unit test for the freshly split-out basic `synth_minidump::List` type to verify that out-of-bounds data is in fact serialized in a batch after the compact list items.
=> Add a test for out-of-bounds lists in SynthMinidump

src/minidump.rs
If `loc.data_size` is the equivalent of a negative number, then in production
builds the end index will wrap around and be smaller than the start index.
The `slice::get` method conveniently checks for all that already, so we can use
that instead.
Note that I left the cast for `end` outside of the addition, since it is
convenient to see the wraparound happen.
=> Fix a panic in location_slice

breakpad-symbols/src/lib.rs, breakpad-symbols/src/sym_file/parser.rs, breakpad-symbols/src/sym_file/types.rs, minidump-common/src/format.rs, minidump-processor/src/process_state.rs, minidump-tools/src/lib.rs, src/context.rs, src/minidump.rs, src/synth_minidump.rs
Rust and Clippy 1.51.0 have new default warnings:
- `clippy::from_over_into` prefers a `From` impl, which comes with a blanked `Into` impl for symmetry.
- `clippy::upper_case_acronyms` enforces [RFC 430 naming guidelines](https://rust-lang.github.io/api-guidelines/naming.html#casing-conforms-to-rfc-430-c-case).
- `rustc_lint::non_fmt_panic` warns against non-format strings as first
argument to `panic!` and related macros. In Rust 2021, this will become a hard
error.
This includes breaking changes in the signature of some public types.
=> Fix acronym and panic warnings

minidump-common/src/format.rs, src/bin/minidump_dump.rs, src/minidump.rs
Implements support for `MinidumpCrashpadInfo` in `minidump_dump`, mostly
equivalent to Breakpad's reference implementation. Breakpad does not
support annotation objects, which we print in a similar fashion.
This is the first time we have to interpret and print the `GUID` type.
Note that the interpretation of these GUIDs is endianness dependent,
which means that byte order of the first three fields is inverted for
little-endian _Minidumps_ independent of the host endianness.
=> Print CrashpadInfo in minidump_dump

minidump-common/src/format.rs, minidump-common/src/lib.rs, src/context.rs, src/lib.rs, src/minidump.rs, src/synth_minidump.rs
This adds Debug derives to most of the library public API.  I have on
occasion missed not having these.
Derives are for now probably good enough, they can be improved as
needed.
----
This in on top of the edition-2018 branch so includes those commits as long as they're not merged.  Only the last commit here is relevant.  It's easy enough to rebase if that branch won't be merged so just let me know.
=> Add missing debug implementations

src/minidump.rs
Self can directly be of lifetime 'a, constraining it to a different
lifetime does not seem to gain any more flexibility.  This simplifies
the signature and thus use.
I don't think there are backwards compatibility concerns with this,
everything which was possible should still be possible.  The lifetime
of the returned stream is still the same 'a as before.
=> Fix memory region and stream lifetimes

minidump-common/src/format.rs, src/minidump.rs, src/synth_minidump.rs, tests/test_minidump.rs
Fixes #16
This is a bit messy because I misunderstood the scope of #16 and started working towards actually walking through the XSAVE entries that MISC_INFO_5 describes before realizing that wasn't actually desired at the moment. So this has some extra "useless" definitions that cover what the meaning of the enabled_features bitfield is, but I figured I'd leave it there in case it's ever desirable to properly process that data.
=> Parse the MISC_INFO_5 format in minidumps

src/minidump.rs
This panics on some minidumps, so instead default to the empty string if the
date is invalid.
=> gracefully fail on invalid dates

minidump-common/src/format.rs, minidump-processor/src/process_state.rs, minidump-processor/src/stackwalker/amd64.rs, minidump-processor/src/stackwalker/amd64_unittest.rs, minidump-processor/src/stackwalker/mod.rs, minidump-processor/src/stackwalker/unwind.rs, minidump-processor/src/stackwalker/x86.rs, minidump-processor/src/stackwalker/x86_unittest.rs
* Fleshes out the skeleton of the unwinder a bit more
* Makes the code of the x86 implementation a bit more agnostic to 32/64-bit
* Adds a basic implementation of a scanning API for x86
* Copies the x86 implementation to provide an amd64 implementation
TODO: tests
Implementation seems to agree with the x64 firefox macos results minidump-stackwalk gets using breakpad (we're mysteriously missing CFI info on that platform, so it's good for testing non-CFI stackwalking).
e.g. "thread 1" on the following minidump demonstrates scanning https://crash-stats.mozilla.org/report/index/5f4f2fd0-a718-4730-bd23-548b00210414
=> Beef up the minidump-processor unwinder

Cargo.toml, minidump-common/Cargo.toml, minidump-common/src/format.rs, minidump-processor/Cargo.toml, minidump-processor/src/bin/minidump_stackwalk.rs, minidump-processor/src/process_state.rs, minidump-processor/src/system_info.rs, src/context.rs, src/minidump.rs, src/system_info.rs
A lot of stuff is just stubbed out, but this gets the basic skeleton setup to iterate on. Fixes #150.
=> Upgrade minidump-stackwalk's frontend and teach it to emit JSON

breakpad-symbols/src/lib.rs, breakpad-symbols/src/sym_file/mod.rs, breakpad-symbols/src/sym_file/parser.rs, breakpad-symbols/src/sym_file/walker.rs, minidump-processor/Cargo.toml, minidump-processor/src/dwarf_symbolizer.rs, minidump-processor/src/process_state.rs, minidump-processor/src/processor.rs, minidump-processor/src/stackwalker/amd64.rs, minidump-processor/src/stackwalker/mod.rs, minidump-processor/src/stackwalker/unwind.rs, minidump-processor/src/stackwalker/x86.rs, src/context.rs
This teaches breakpad-symbols to parse and evaluate STACK CFI exprs, and plumbs it through to the amd64/x86 stack walkers in minidump-processor. As a result, cfi-based unwinding now works on linux. [Example minidump-processor output on a firefox minidump](https://gist.github.com/Gankra/997852c049b197975045476e5d8ce099).
To do this, it introduces a FrameWalker trait in breakpad-symbols that abstracts away the details of mapping string register names to loads/stores from the context.
minidump-processor in turn introduces a CfiStackWalker that implements FrameWalker by generically wrapping up the callee's Context and a fresh caller Context. The Context trait is also beefed up to expose the necessary details.
Incidentally this also gives everything needed to implement cfi unwinding on ARM64, …
=> Implement STACK CFI unwinding for x86/x64 (and part of STACK WIN)

minidump-common/src/format.rs, minidump-processor/src/process_state.rs, minidump-processor/src/processor.rs, src/minidump.rs, src/synth_minidump.rs
This also introduces the notion of an 'extended list', which is a format that several
newer sections implement but we hadn't happened to use yet. Most of this code is just
copy-pasting the normal Module and List code.
This is the minimal impl of #168, but ideally we'd use this info for unwinding/symbolication too
=> Add support for the unloaded modules stream.

minidump-processor/src/processor.rs, src/minidump.rs, tests/test_minidump.rs
Fixes #19
I'm a bit fuzzy on what parts should be in minidump vs minidump_processor -- I kinda settled on "the parts that use scroll or resolve rva's should go in minidump"
=> Implement cpu_info/os_ver

minidump-common/src/format.rs, minidump-processor/src/process_state.rs, minidump-processor/src/processor.rs, src/minidump.rs
Fixes #22
Note that this punts on properly outputting NTSTATUS/FAST_FAIL values for now, because @gabrielesvelto was planning a bunch of work in that area anyway.
This is a big gross mess, made much worse by massive indentation and very long type names. I don't *love* the hack of using Debug output since it's Not Guaranteed, but the alternative is just such an enormous amount of messy hard-to-maintain copy-pasting.
=> Implement CrashReason for Windows/Linux/MacOs

Cargo.lock, minidump-common/src/format.rs, minidump-processor/src/process_state.rs, minidump-processor/src/processor.rs, minidump-processor/src/stackwalker/mod.rs, minidump/Cargo.toml, minidump/src/minidump.rs, minidump/src/synth_minidump.rs
Firefox minidumps don't appear to populate this, even on Windows, but we should move to using it instead of our hacky side-json.
Fixes #173
=> Add support for ThreadNamesStreams

breakpad-symbols/src/lib.rs, breakpad-symbols/src/sym_file/parser.rs, breakpad-symbols/src/sym_file/types.rs, breakpad-symbols/src/sym_file/walker.rs, minidump-common/src/format.rs, minidump-common/src/traits.rs, minidump-processor/src/processor.rs, minidump-processor/src/stackwalker/arm.rs, minidump-processor/src/stackwalker/arm64.rs, minidump-processor/src/stackwalker/arm64_old.rs, minidump-processor/src/stackwalker/arm64_unittest.rs, minidump-processor/src/stackwalker/arm_unittest.rs, minidump-processor/src/stackwalker/mod.rs, minidump/src/context.rs, minidump/src/minidump.rs
The code for all 3 is identical for now. I'm pretty sure the framepointer/scan code is wrong for 32-bit ARM, to be iterated on more later. I added the 32-bit ARM stuff as a bit of an afterthought when I encountered it while testing on some firefox minidumps.
This also includes two commits that fixup other stuff I ran into while testing these.
=> Add unwinders for ARM, ARM64, and ARM64_OLD 

minidump-common/src/format.rs, minidump-processor/src/process_state.rs, minidump-processor/src/processor.rs, minidump/src/minidump.rs
I've wanted to this to quickly identify what stuff we're getting in our dumps but doing nothing with. The unimplemented_streams function also serves as a good TODO list :)
Also I currently only report these in the --human format, because I don't want to extend the json format without more serious consideration.
=> Add support for reporting unknown/unimplemented streams

Cargo.lock, breakpad-symbols/src/lib.rs, minidump-processor/Cargo.toml, minidump-processor/src/dwarf_symbolizer.rs, minidump-processor/src/lib.rs, minidump-processor/src/process_state.rs, minidump-processor/src/processor.rs, minidump-processor/src/stackwalker/amd64_unittest.rs, minidump-processor/src/stackwalker/arm64_unittest.rs, minidump-processor/src/stackwalker/arm_unittest.rs, minidump-processor/src/stackwalker/mod.rs, minidump-processor/src/stackwalker/x86_unittest.rs, minidump-processor/src/symbols.rs, minidump-processor/tests/test_processor.rs, minidump-stackwalk/Cargo.toml, minidump-stackwalk/src/main.rs
To test the symbolic mode I recommend just flipping the "default-features" value in minidump-processor's Cargo.toml
=> Make a shim for toggling between breakpad and symbolic

minidump-common/src/format.rs, minidump-processor/src/process_state.rs, minidump-processor/src/processor.rs, minidump/src/minidump.rs
Fixes #175 
A bit of a mess because I had to copy the MISC_INFO multi_struct macros to fit this new format.
Also I did some drive-by cleanups on format.rs -- that one bitflags got shunted to the bottom of the file because it breaks syntax highlighting and that was making it harder to read my macro nightmares.
`MINIDUMP_LOCATION_DESCRIPTOR` got a `From<u8>` impl because that's what pread_derive uses for Array default.
=> Add support for MozMacosCrashInfoStream

breakpad-symbols/src/lib.rs, breakpad-symbols/src/sym_file/walker.rs, minidump-processor/src/stackwalker/amd64.rs, minidump-processor/src/stackwalker/amd64_unittest.rs, minidump-processor/src/stackwalker/arm.rs, minidump-processor/src/stackwalker/arm64.rs, minidump-processor/src/stackwalker/arm64_old.rs, minidump-processor/src/stackwalker/arm64_unittest.rs, minidump-processor/src/stackwalker/arm_unittest.rs, minidump-processor/src/stackwalker/mod.rs, minidump-processor/src/stackwalker/x86.rs, minidump-processor/src/stackwalker/x86_unittest.rs, minidump-processor/src/symbols.rs, minidump/src/context.rs
Some notable changes:
* Callee-saved registers are now forwarded by default (except stack pointer and instruction pointer)
* FrameWalker now has a `clear_caller_register` method to allow the CFI walker to delete forwarded callee-saved registers (e.g. when the register has a rule but it doesn't eval properly) 
* ARM(32) unwinder now allows stack frames to have the same `sp` value (stacks is not strictly monotonic), matching ARM64 behaviour
* get_register for MinidumpContextValidity::All now properly checks that the requested register is part of the context's register list
This notably omits the STACK WIN tests in `stackwalker_x86_unittest.cc` because I don't have a working implementation of that format and those tests are far less regular than the CFI ones.
=> Forward Callee-Saved Regs + Add A Million CFI Tests

minidump/src/bin/minidump_dump.rs, minidump/src/minidump.rs
This is a simple patch to print out the thread names stream. I'm using it to test my macOS thread names' writer.
=> Support printing out the contents of the thread names stream

minidump-processor/src/symbols.rs
This would allow us to implement caching without resorting to internal mutability.
=> SymbolSupplier::locate_symbol: Take self by mut ref

minidump-common/src/format.rs
=> Print out the exception code of Linux signals sent from userspace / kernel correctly

breakpad-symbols/src/lib.rs, breakpad-symbols/src/sym_file/parser.rs, breakpad-symbols/src/sym_file/types.rs
Fixes #262
INFO lines are the 'standard' way to add things to a breakpad symbol file that other parsers can ignore.
=> Read and write an INFO URL line for cached files

minidump-common/src/format.rs, minidump-processor/src/processor.rs, minidump/src/minidump.rs, minidump/src/synth_minidump.rs
This is a dump of /proc/self/maps from the crashing process. Details on the format
included in the comments. Because this info does a similar thing to MinidumpMemoryInfoList
I have also introduced a UnifiedMemoryInfo type which you can use to wrap the two up
and not deal with the differences.
minidump_processor now reads both streams and sets up a UnifiedMemoryInfo, but it doesn't
yet do anything with it. Also did some cleanup on the previous patch that I noticed while
designing the unified API.
Part of #256
=> Implement LinuxMaps stream

minidump-processor/src/process_state.rs, minidump-processor/src/processor.rs, minidump-processor/src/system_info.rs, minidump/src/minidump.rs, minidump/src/synth_minidump.rs
Fixes #207
Adds implementations for:
* LinuxCpuInfo (/proc/cpuinfo)
* LinuxProcStatus (/proc/self/status)
* LinuxEnviron (/proc/self/environ)
The only new data we collect is LinuxCpuInfo.microcode_version, which gets fed through to
cpu_microcode_version in the json schema. All the code for the other streams is written,
so it should now be trivial to grab whatever key we decide is interesting with only a few
new lines.
LinuxAuxv, LinuxCmdLine and LinuxDsoDebug have been excluded from
this patchset as they all have more custom formats than the KEY SEPARATOR VALUE formats
of the implemented streams.
(This PR is built on top of the previous one to avoid merge conflicts, only the second patch is new.)
=> Stub out implementations of the stringy linux streams

README.md, RELEASES.md, minidump-common/src/format.rs, minidump-processor/src/processor.rs, minidump-tools/src/lib.rs, minidump/src/bin/minidump_dump.rs, minidump/src/context.rs, minidump/src/minidump.rs, minidump/tests/test_minidump.rs, synth-minidump/src/lib.rs
This is an alternative version of #278, which instead of weird magic traits that will do double-parsing behind your back, we just defer parsing the context/stack_memory until the user requests them, at which point we can demand dependent streams to do the task properly. I realized this was a reasonable approach when I made a similar api for #286.
Using this info for contexts is only stubbed out, but stack repair is implemented.
This is basically no extra burden to a legitimate user since they're going to want to parse out MemoryList and SystemInfo, and MiscInfo is optional. It's slightly more annoying for tests because we need to mock SystemInfo. For now I used the sloppy garbage SystemInfo I made for Linux integration tests in `processor`. I'll deal with it when I implement actually …
=> WIP Lazily parse stack memory and cpu contexts

breakpad-symbols/src/lib.rs, minidump-processor/src/symbols.rs, minidump-stackwalk/src/main.rs, minidump-tools/src/lib.rs
This also introduces a --symbol-download-timeout-secs flag to minidump-stackwalk
so it's configurable. The default is 1000 seconds (which for a 300MB .sym file
requires a connection speed of 300KB/s).
Weirdly I think adding the timeout at all seems to unstick the download, but I'm
not sure. Either way you can tune the value to your needs.
Fixes #300
=> Add a timeout to symbol downloads

minidump-stackwalk/src/main.rs, minidump/src/bin/minidump_dump.rs, minidump/src/minidump.rs
Our error types have Display strings but we weren't using them. For a couple strings
I've added a parenthetical hint, reflecting the common cause of these two errors
(from what I'm seeing in socorro).
I've also added some `warn`s for duplicate entries, to hopefully make it easier
to notice when this happens. In particular socorro gets many MissingThreadList
minidumps which are just full of 13 dummy UnusedStream entries. Looking at the
minidump in minidump_dump is really confusing, because it says there's 13 but
only prints 1. The logs now make it clearer, as you see several copies of:
```
[WARN] Minidump contains multiple streams of type 0 (UnusedStream) at indices 0 (0 bytes) and 1 (0 bytes) (using 1)
```
(It will still be confusing to look at in minidump_dump, we should really hook it …
=> Give better feedback on corrupt minidumps 

minidump/src/lib.rs, minidump/src/minidump.rs
I was gonna do more cleanup on individual types and methods but the top level docs (which seemed more important) completely wiped me out.
=> add a bunch of docs to minidump

Cargo.lock, RELEASES.md, breakpad-symbols/Cargo.toml, minidump-common/Cargo.toml, minidump-processor/Cargo.toml, minidump-stackwalk/Cargo.toml, minidump/Cargo.toml, synth-minidump/Cargo.toml
The JSON schema and minidump-stackwalk CLI are now stabilized. They are now
reasonable to rely on in production (only reason we would break them is if
we ran into a nasty bug).
This release also adds a ton of documentation! (But there can always be more...)
See RELEASES.md for details
=> 0.9.5 release

minidump-stackwalk/src/main.rs
There are 3 different binaries which call themselves minidump-stackwalk
1. breakpad's minidump-stackwalk (human output)
2. mozilla's minidump-stackwalk (json output)
3. rust-minidump's minidump-stackwalk (both)
This implementation (mdsw 3) was primarily designed to replace mdsw 2, so
default to json output was "natural". However mdsw 1 is actually run locally
and in the wild more, so emulating their interface is probably the
better default, even if the json output is the "first-class" output.
This will be part of the 0.9.6 release, and is a fairly major breaking change,
but also fairly trivial to handle downstream -- just pass the --json flag.
Note that minidump-stackwalk 0.9.5 introduced --json even while it was the
default, so you can more easily handle this transition by always …
=> Make --human the default output of minidump-stackwalk 

Cargo.lock, README.md, minidump-processor/Cargo.toml, minidump-processor/README.md, minidump-processor/src/lib.rs, minidump-processor/src/process_state.rs, minidump-stackwalk/README.md, minidump/README.md, minidump/src/lib.rs
Although this is mostly copying/moving examples and docs from other locations, including socc-pair.
A lot of corrections were made to old information in READMEs though.
=> you can never stop me from writing more docs

Cargo.lock, breakpad-symbols/Cargo.toml, breakpad-symbols/src/lib.rs
50% chance this elides an enormous copy and a bunch of reallocations, but no idea.
The async branch needs this anyway so no harm to do it now.
=> Use reqwest's Bytes type instead of copying into a Vec

breakpad-symbols/src/sym_file/parser.rs, minidump-processor/src/processor.rs, minidump-stackwalk/tests/test-minidump-stackwalk.rs, minidump/README.md, minidump/src/minidump.rs, synth-minidump/src/lib.rs
This is a minor breaking change, as get_crash_address now requires a Cpu.
Also adds some minimal Exception support to synth-minidump.
Fixes #360
=> Don't trust high bits of crash addresses

Cargo.lock, breakpad-symbols/Cargo.toml, breakpad-symbols/src/lib.rs, breakpad-symbols/src/sym_file/mod.rs, breakpad-symbols/src/sym_file/parser.rs
This changes the breakpad-symbols parser to stream its input. This allows us to:
* Avoid ever manifesting the entire (~GB) symbol file in memory
* Parse as the file downloads
* Save to the cache as the file downloads
* Theoretically eliminate a ton of (re)allocations and copies
See breakpad_symbols/src/syms/mod.rs : SymbolFile::parse for discussion of the design
=> Streaming Symbol Parser

minidump-common/src/format.rs, minidump/src/minidump.rs
This should fix #381 and fix #326
=> fix: Guard memory reservations with bounds checks

Cargo.lock, breakpad-symbols/Cargo.toml, breakpad-symbols/src/lib.rs, breakpad-symbols/src/sym_file/mod.rs, breakpad-symbols/src/sym_file/parser.rs, minidump-processor/Cargo.toml, minidump-processor/src/processor.rs, minidump/Cargo.toml, minidump/src/minidump.rs
fixes #371
This is technically a breaking change, as it removes stuff from existing Error types.
=> ref: Replace failure by thiserror, making Errors std compatible

minidump-processor/src/process_state.rs, minidump-processor/src/processor.rs, minidump-processor/src/system_info.rs, minidump-processor/tests/test_processor.rs
The processor joins the operating system version and build into a single field.
While this is a common way to represent the version, it is convenient to have
them separate.
=> Process OS build into a dedicated field

minidump-processor/src/process_state.rs, minidump-processor/src/processor.rs, minidump-processor/src/stackwalker/mod.rs
The `thread_id` is part of the raw minidump thread structure, but not the processed `CallStack`. This is an inconvenience when dealing with the process state.
If preferred, we could also add the raw thread structure as field to `CallStack`.
=> Add thread_id to CallStacks in the ProcessState

minidump-processor/src/stackwalker/amd64_unittest.rs, minidump-processor/src/stackwalker/arm.rs, minidump-processor/src/stackwalker/arm64_unittest.rs, minidump-processor/src/stackwalker/arm_unittest.rs, minidump-processor/src/stackwalker/x86.rs, minidump-processor/src/stackwalker/x86_unittest.rs
Fixes #422
This issue is kinda nonsense, but in a 'hey good job fuzzer for finding this wild input' kinda way?
Basically rust-minidump likes doing things in 64-bit to reuse code and keep things uniform, but this
creates a fun situation where you can define *impossible* memory ranges for a 32-bit system and have
calculated pointers successfully access that memory because the operations are happening in 64-bit.
In-and-of-itself this is not a problem, but it does mean that things can go Bad when you have some
of the operations happening in the platform's native width, causing some operations to succeed and
others to overflow. In particular, this would allow you to load some memory that is beyond u32::MAX
(which normally would be a strong proof that the entire memory range is a valid pointer) …
=> Harden 32-bit unwinders against mixed-width calculations.

minidump/src/minidump.rs
The fuzzer found yet another overflow.
We *could* make `MinidumpMemory` check for `self.base_address + self.size` being in bounds on construction, but I guess it's better to do it when you actually go to *use* it, since directly asking for the base address/size still works.
Still, that leads to cases like this.
=> Avoid overflow in bounds check of MinidumpMemory

minidump-common/src/format.rs, minidump/src/minidump.rs
This includes a few different changes:
* If the exception records' si_code is 0 just print the signal name and omit the hexadecimal value of si_code (this was Breakpad's behavior)
* For signals that have been delivered by users (si_code <= 0) print the corresponding flag (e.g. SI_USER, SI_TKILL, etc...)
* For signals that have been sent from "somewhere" within the kernel  (si_code == 0x80) print SI_KERNEL
* Add human-readable si_code values for SIGTRAP and SIGSYS
=> Improve how Linux signals are printed out

Cargo.lock, README.md, breakpad-symbols/Cargo.toml, breakpad-symbols/src/lib.rs, breakpad-symbols/src/sym_file/mod.rs, minidump-processor/Cargo.toml, minidump-processor/README.md, minidump-processor/src/lib.rs, minidump-processor/src/processor.rs, minidump-processor/src/stackwalker/amd64.rs, minidump-processor/src/stackwalker/amd64_unittest.rs, minidump-processor/src/stackwalker/arm.rs, minidump-processor/src/stackwalker/arm64.rs, minidump-processor/src/stackwalker/arm64_old.rs, minidump-processor/src/stackwalker/arm64_unittest.rs, minidump-processor/src/stackwalker/arm_unittest.rs, minidump-processor/src/stackwalker/mod.rs, minidump-processor/src/stackwalker/unwind.rs, minidump-processor/src/stackwalker/x86.rs, minidump-processor/src/stackwalker/x86_unittest.rs, minidump-processor/src/symbols.rs, minidump-processor/tests/test_processor.rs, minidump-stackwalk/Cargo.toml, minidump-stackwalk/src/main.rs
I was curious how bad this was and then suddenly I was "done" lol
This compiles and correctly handles amd64.
TODO: 
* ~~[ ] test `#[tokio::main(flavor = "current_thread")]`~~ (perf analysis came back good enough that I don't care)
=> WIP make symbolication async

breakpad-symbols/fuzz/fuzz_targets/cfi_eval.rs, minidump-processor/fuzz/fuzz_targets/process.rs, minidump-processor/fuzz/fuzz_targets/walk_stack.rs, minidump-processor/fuzz/src/lib.rs
Also run fmt because CI doesn't check formatting inside fuzzing targets.
=> Actually await in the process

minidump-common/src/format.rs, minidump/src/lib.rs
The links to various MSDN docs in the minidump parser are now broken, thanks to two changes:
1. The `/desktop` part of the path has been renamed to `/win32`
2. The leading underscore from the struct names have been stripped from the URL
Certain URLs will be correctly redirected if they're only affected by the first change, i.e. https://docs.microsoft.com/en-us/windows/win32/Memory/memory-protection-constants. I've opted to update those regardless just to keep everything up to date.
URLs affected by both changes lead to a 404, hence this PR. I've double checked the links to make sure they actually work as advertised, ie they go somewhere useful and the name of the struct matches. I didn't check to make sure that the contents of the structs match up, however.
=> Fix up links to MSDN docs

minidump-processor/src/stackwalker/mod.rs
When stack scanning, we want to validate the address _before_ the return address, which is usually the address of the function call. Breakpad uses this heuristic, see https://github.com/google/breakpad/commit/087795c851d269a49baf6cd0fb886c2990729f44.
We have a test case where `rust-minidump` stack scanning returns a clearly incorrect frame with a suspiciously aligned address, see this github check: https://github.com/getsentry/symbolicator/runs/5144569674?check_suite_focus=true#step:5:3147. This PR would fix this case.
=> Stack scanning: decrement address before lookup

minidump-common/src/format.rs, minidump-processor/tests/test_processor.rs, minidump/src/minidump.rs
This is related to the initiative outlined in https://github.com/getsentry/symbolicator/issues/620.
This PR fills in the currently incomplete implementation of `code_identifier` as well as a subsection of `debug_identifier` on macOS/Solaris(/maybe iOS, NaCl, PS3) minidump modules. The way this is done is by relying on the assumption that the `age` field on a module's CV record is only ever `0` if the minidump was created by Breakpad on a non-Windows device. See Breakpad's minidump writer for [macOS](https://github.com/google/breakpad/blob/main/src/client/mac/handler/minidump_generator.cc#L1468-L1486) and [Solaris](https://github.com/google/breakpad/blob/main/src/client/solaris/handler/minidump_generator.cc#L474-L488).
The reason why I'm depending on this rather fragile behaviour is …
=> Return more correct code/debug identifiers for macOS minidumps

minidump-processor/src/stackwalker/arm.rs, minidump-processor/src/stackwalker/arm64.rs, minidump-processor/src/stackwalker/arm64_old.rs, minidump-processor/src/stackwalker/arm_unittest.rs, minidump/src/context.rs
Adds a `registers` and `valid_registers` iterator to all context types, as well as the general `MinidumpContext` type. This makes it possible to enumerate registers in a generic way without special-casing the concrete context types on usage site. The register name constants are moved to an associated constant in the trait.
=> Implement register iterators for all context types

Cargo.lock, breakpad-symbols/Cargo.toml, minidump-common/Cargo.toml, minidump-processor/Cargo.toml, minidump/Cargo.toml, minidump/src/minidump.rs
The previous implementation did not correctly represent the DebugId of
(very old) PDB 2.0 PE files.  The new debugid release suppots these
correctly.
=> Fix PDB 2.0 DebugId format

minidump/src/minidump.rs
The minidump processor currently returns modules with debug ids of `Some(00000000-0000-0000-0000-000000000000)`. This fixes that case by checking that the `build_id` is not just a list of zeros.
=> MinidumpModule: Don't return DebugId for invalid build_id

minidump-common/src/format.rs, minidump/src/minidump.rs
=> Correct the values of the Windows CE stream types to prevent clashes with future Windows stream types.

minidump/src/minidump.rs
=> Use raw bytes to represent trailing whitespace in tests so that it doesn't get auto-trimmed by editors

minidump-processor/src/process_state.rs, minidump-processor/src/stackwalker/x86_unittest.rs
The `instruction_address` field already has heuristics applied, mostly
substracting the size of an instruction, to point to the caller rather than the
return address. Breakpad additionally exposed the unmodified `return_address`
which can be useful at times.
Since `instruction_address` starts with the return address and then modifies it
during stack walking, the only change needed is to retain an unmodified copy.
=> Expose original return address in ProcessState

minidump-common/src/format.rs, minidump-stackwalk/src/main.rs, minidump/fuzz/fuzz_targets/parse.rs, minidump/src/lib.rs, minidump/src/minidump.rs, minidump/tests/test_minidump.rs, synth-minidump/src/lib.rs
I happened to need to read a full dump and found this missing in the library, so I implemented it.
To reuse the existing code, I abstracted some functions on `MinidumpMemoryList` into a generic type `MinidumpMemoryListGeneric`, and made both `MinidumpMemoryList` and the new `MinidumpMemory64List` type aliases of the generic type.
=> Implement MinidumpMemory64List stream

minidump-processor/src/stackwalker/arm.rs, minidump-processor/src/stackwalker/arm64.rs, minidump-processor/src/stackwalker/arm_unittest.rs
This aligns frame pointer unwinding on ARM64 more closely with the way breakpad works, to wit: if the previous frame pointer was 0, rust-minidump currently short-circuits because it can't get the values of `fp` and `lr` from that address. Breakpad, on the other hand, soldiers on and simply sets those registers to 0 as well. As a consequence, the frame pointer unwind succeeds in breakpad, while rust-minidump falls back to stack scanning. I honestly don't know if that makes sense—the reason I implemented this PR is because this difference in behavior is behind #481. Thoughts, @Gankra @jan-auer?
=> ARM64: Emulate breakpad for 0 frame pointers

minidump-processor/fuzz/fuzz_targets/walk_stack.rs, minidump-processor/src/processor.rs, minidump-processor/src/stackwalker/amd64.rs, minidump-processor/src/stackwalker/amd64_unittest.rs, minidump-processor/src/stackwalker/arm.rs, minidump-processor/src/stackwalker/arm64.rs, minidump-processor/src/stackwalker/arm64_old.rs, minidump-processor/src/stackwalker/arm64_unittest.rs, minidump-processor/src/stackwalker/arm_unittest.rs, minidump-processor/src/stackwalker/mod.rs, minidump-processor/src/stackwalker/unwind.rs, minidump-processor/src/stackwalker/x86.rs, minidump-processor/src/stackwalker/x86_unittest.rs
Using this, the Unwind implementations can apply heuristics
based on the platform-specific calling conventions.
=> ref: Pass SystemInfo through to Unwind impls

breakpad-symbols/fuzz/fuzz_targets/cfi_eval.rs, breakpad-symbols/src/lib.rs, breakpad-symbols/src/sym_file/walker.rs, minidump-processor/src/stackwalker/amd64.rs, minidump-processor/src/stackwalker/arm.rs, minidump-processor/src/stackwalker/arm64.rs, minidump-processor/src/stackwalker/arm64_old.rs, minidump-processor/src/stackwalker/mod.rs, minidump-processor/src/stackwalker/x86.rs
This method is used as a proxy for whether the callee is the context frame. See https://github.com/luser/rust-minidump/pull/490.
=> FrameWalker: Add has_grand_callee method

minidump-common/src/format.rs, minidump/src/minidump.rs
- Derive Default for MINIDUMP_DIRECTORY
- Minor cleanup while debugging something
- Derive Pwrite for many minidump structs
- Add amd64 context flags and derive a few more pwrite
This PR adds derives for many (only iterating with x86_64 atm) structs so that they can be written. The particular use case was for https://github.com/EmbarkStudios/minidump_writer_linux/commit/04d22cfd030bf1df2705cf250f13b4a3f0771656 which allowed me to get rid of a massive amount of duplicated type definitions that the code had. I noticed during the refactor that there were no bitflags for the context_flags values in CONTEXT_AMD64, so I added that as well, but I'm a bit iffy on the naming.
=> Add pwrite derives

minidump-processor/src/processor.rs, minidump-stackwalk/src/main.rs, minidump/src/minidump.rs
This is the last blocker for *finally* cutting a release.
=> Properly define error names instead of sloppily leaning on debug formatting

minidump/src/minidump.rs
This adds an `os: Os` field to `MinidumpModule` that can be used for e.g. `code_identifier`.
Builds on https://github.com/luser/rust-minidump/pull/497. Fixes https://github.com/luser/rust-minidump/issues/474.
The `test_macos_ids()` test fails despite my changes—I think I'm setting the OS to MacOs correctly, but `Minidump::read` somehow interprets it as `Unknown`.
=> MinidumpModule: use system info for OS detection.

minidump-processor/src/process_state.rs, minidump-stackwalk/tests/snapshots/test_minidump_stackwalk__dump.snap, minidump/src/minidump.rs, minidump/src/system_info.rs
In particular, this adds support for reading the CPU type and fixes some issues related to big-endian, such as UTF16 parsing, and DebugId parsing.
The Module DebugId parsing is now done at parsing-time because it needs to be endian aware.
For sentry folks, this fixes:
* Unknown minidump arch 1: https://sentry.my.sentry.io/organizations/sentry/issues/297362
* Garbage module names for example: https://sentry.my.sentry.io/organizations/sentry/issues/297548/events/99e6508a508744dd8aa19a06c57e5d23/
I’m a bit unsure how to write a unit-test for all this with reasonable effort 🤷🏻‍♂️
=> feat: Add rudimentary MIPS support

breakpad-symbols/src/lib.rs, breakpad-symbols/src/sym_file/mod.rs, minidump/src/minidump.rs
This teaches the parser to resize its buffer up to a reasonably maximum limit, and then if a line
slams into that maximum, it just enters a PANIC RECOVERY mode where it discards bytes until it
finds a newline or EOF, then resumes normal behaviour. This basically just ends up discarding horrible
enormous (80kb+) symbols instead of discarding the entire file.
Also this adds a bunch of "symbol:" TRACE logs to make figuring this stuff out easier in the future. In particular if we *do* end up discarding a bunch of your lines, that will be noted in the TRACE at least.
=> Make the parser much more robust to enormous symbols.

Cargo.lock, breakpad-symbols/src/lib.rs, minidump-common/src/lib.rs, minidump-common/src/utils.rs, minidump-processor/Cargo.toml, minidump-processor/src/process_state.rs
=> Use only the file name when sending the code file to a symbol server

Cargo.lock, breakpad-symbols/Cargo.toml, breakpad-symbols/fuzz/Cargo.lock, breakpad-symbols/src/http.rs, breakpad-symbols/src/lib.rs, breakpad-symbols/src/sym_file/mod.rs, minidump-processor/Cargo.toml, minidump-processor/fuzz/Cargo.lock, minidump-processor/src/symbols.rs, minidump-stackwalk/Cargo.toml
This makes it so that retrieving symbols via HTTP is optional, eg. https://github.com/rust-minidump/minidump-writer/pull/21#discussion_r861912364 only wants to process symbols files that are present on the local disk for testing purposes, making HTTP optional removes a large number of unnecessary dependencies to speed up CI builds.
This _also_ nukes OpenSSL in favor of using `rustls` due the many aggravations that come with OpenSSL, some of which have had previous [commits](https://github.com/rust-minidump/rust-minidump/commit/a142f208f9d2899be3ca168aa1de0bb43dcffef3) to workaround. `rustls` on the other hand doesn't have really, any aggravations, at least that we have found in 3+ years of usage, everything just works better, including cross compilation and other scenarios that openssl is …
=> Make breakpad-symbols HTTP retrieval optional

Cargo.lock, breakpad-symbols/Cargo.toml, breakpad-symbols/fuzz/Cargo.lock, minidump-common/Cargo.toml, minidump-processor/Cargo.toml, minidump-processor/fuzz/Cargo.lock, minidump-stackwalk/tests/snapshots/test_minidump_stackwalk__long-help.snap, minidump-stackwalk/tests/snapshots/test_minidump_stackwalk__markdown-help.snap, minidump-stackwalk/tests/snapshots/test_minidump_stackwalk__short-help.snap, minidump/Cargo.toml, minidump/fuzz/Cargo.lock, minidump/src/minidump.rs
This is technically a breaking change, as these types are exposed in public API.
=> deps: Update debugid/uuid dependencies

breakpad-symbols/src/sym_file/types.rs
The derived implementation is a lexicographical order based on the struct field order.
=> Derive Ord on PublicSymbol automatically

minidump-common/src/format.rs, minidump-processor/src/stackwalker/mips.rs
I believe the `get_caller_for_leaf` function is unsound: it passes the stack pointer on unchanged to the caller. This is correct for leaf functions that don't use the stack at all, but for those that do, there's no way to recover the stack pointer in the absence of CFI.
I also attempted to replicate Breakpad's stackscanner for MIPS, but I'm not sure Breakpad even does remotely the right thing here. On other architectures you can stack scan because when you find a return address, you know that it was pushed on the stack just before the call to the current function. This lets you recover the stack pointer at the time of the call. But on MIPS, RA is saved on the stack in the caller's prologue, not just before the call, so finding a return address tells you nothing about the stack at the time …
=> Various fixes & an attempt at stack scanning

breakpad-symbols/src/sym_file/parser.rs
Turns out that "multispace" does not mean "multiple spaces", it means "more than just spaces, including \r and \n".
With `multispace1` we could accidentally eat more than just a single line, if we encountered a corrupted line which happened to be truncated at a position where we were expecting a space.
=> Fix space handling in nom parser, by using space1 instead of multispace1

minidump-processor/src/stackwalker/arm64.rs, minidump-processor/src/stackwalker/arm64_old.rs, minidump-processor/src/stackwalker/arm64_unittest.rs
The proper value for a system can be found with
```
% sysctl machdep.virtual_address_size
```
Which on the machine mstange tested yields 47. We were seeing 40 being too low in practice
for JIT code pages. Ideally this is information that the minidump_writer should stuff somewhere
so that we can precisely do this. Apparently crashpad already does this somewhere but I lost
track of that message.
=> bump the apple ptr-auth real bits to 47

minidump-processor/Cargo.toml, minidump-processor/src/symbols.rs
As a first step to follow up on the discussions in https://github.com/rust-minidump/rust-minidump/pull/576.
This just removes the two feature flags and the unused/incomplete symbolic-syms code completely.
Its a first step and we can do more simplifications on top of this later.
=> ref: Remove unused symbolic-shim

breakpad-symbols/src/sym_file/mod.rs, breakpad-symbols/src/sym_file/parser.rs, breakpad-symbols/src/sym_file/types.rs
This parses the new format but produces the same output as before.
So with this patch alone, we will not get any inline information in the
output.
But this patch allows us to switch to the new sym format without
breaking anything (hopefully).
In `fill_symbol` we now call `get_outermost_source_location`, which has
to look at the inline information, because just by looking at the lines
you would not get the same output as before with the new sym files.
That's because, when inline information is present in sym files, the
line records now describe the lines *at the deepest level of inlining*.
In sym files without inline information, the line records describe the
lines at the outermost level.
=> Add support for parsing INLINE_ORIGIN and INLINE.

breakpad-symbols/src/lib.rs, breakpad-symbols/src/sym_file/types.rs, minidump-common/src/errors/linux.rs, minidump-common/src/errors/macos.rs, minidump-common/src/errors/windows.rs, minidump-common/src/format.rs, minidump-processor/src/process_state.rs, minidump-stackwalk/src/main.rs, minidump-stackwalk/tests/snapshots/test_minidump_stackwalk__dump-brief.snap, minidump-stackwalk/tests/snapshots/test_minidump_stackwalk__long-help.snap, minidump-stackwalk/tests/snapshots/test_minidump_stackwalk__markdown-help.snap, minidump-stackwalk/tests/snapshots/test_minidump_stackwalk__short-help.snap, minidump-stackwalk/tests/test-minidump-stackwalk.rs, minidump/src/context.rs, minidump/src/minidump.rs, minidump/src/system_info.rs
While that stuff is useful when you need it, it takes really long to print out all the memory in a firefox minidump, completely dwarfs anything else, and usually isn't what I'm looking for, personally.
=> Make --brief work for --dump to omit hexdumps 

RELEASES.md
Tweak the release notes to say that 0.12 won't include inline frames and just exists to be compatible with the new format without observable changes.
I've moved the WIP text to a new 0.13 section.
r? @Gankra
=> Tweak release note text for inline support

Cargo.lock, breakpad-symbols/src/lib.rs, minidump-processor/Cargo.toml, minidump-processor/src/processor.rs, minidump-processor/src/symbols.rs
This makes the inner loop that processes and stackwalks all minidump threads
concurrent using join_all concurrency. This could possibly reduce the time to process
a minidump if there is IO involved in fetching symbols for different modules concurrently.
I extracted this code from #601 with minimal modifications, so credit goes to @Gankra ;-)
The PR also adds docs for the `SymbolProvider` to clarify what its purpose and requirements are.
=> ref: Process threads concurrently

minidump/src/minidump.rs
Platform detection in `code_identifier` erroneously only checked for `Os::MacOs` and let `Os::Ios` fall through to the windows case.
=> Fix code_identifier for iOS

minidump-processor/json-schema.md
This rectifies the spec in regards to where register information is emitted.
Fixes #639.
=> Fix json schema re: registers

.github/workflows/release.yml, Cargo.toml, RELEASES.md, minidump-stackwalk/Cargo.toml, minidump-stackwalk/tests/test-minidump-stackwalk.rs
With these changes, if you type:
```
cargo release 0.15.0 --execute
```
It will:
* update all the versions in Cargo.tomls
* update a bunch of version strings in RELEASES and snapshot tests
* tag v0.15.0
* push to main (with the tag)
* cargo publish
Then CI will see the tag and:
* create a github release with the notes from RELEASES.md
* create tarballs/zips for windows/macos/linux * x64/arm64
This makes the main chore of a release "making sure the "Next Release" entry has the releases notes you want (manual, intentionally). Potentially this should have a post-release hook to add the commit SHA as I currently do manually... problem for later.
=> add release workflow

breakpad-symbols/src/sym_file/parser.rs
While investigating #740 I figured out the issue was that the parser errors out on empty
lines in symfiles. This is fixed in this PR.
Note that there might be a nicer way to solve this, but I do not have much experience with Nom,
so any hints how to improve this are welcome.
=> Fix parsing symfiles that contain empty lines

minidump-stackwalk/Cargo.toml
Cargo release was broken by accident when updating clap in 06348c251b3165741a6a6e744f02baef5da6c64d which removed the version line (Version: `minidump-stackwalk 0.14.0`) from the output, but missed removing the version number replacement in pre-release-replacements.
Fixes the issue observed in #724
=> Fix cargo-release replacements

CONTRIBUTING.md, minidump-processor/src/evil.rs, minidump-processor/src/process_state.rs, minidump-processor/src/processor.rs
This reads the CPUMicrocodeVersion field from `--evil-json` and uses that if no other microcode version information is available in the minidump. It also changes output to print the microcode version as a hex string.
Closes #683.
One thing that isn't clear: should the output microcode version be 0-padded or not?
=> Improve the handling of CPU microcode values.

README.md, minidump-processor/fuzz/fuzz_targets/walk_stack.rs, minidump-processor/src/arg_recovery.rs, minidump-processor/src/op_analysis.rs, minidump-processor/src/processor.rs, minidump-processor/src/stackwalker/amd64.rs, minidump-processor/src/stackwalker/amd64_unittest.rs, minidump-processor/src/stackwalker/arm.rs, minidump-processor/src/stackwalker/arm64.rs, minidump-processor/src/stackwalker/arm64_old.rs, minidump-processor/src/stackwalker/arm64_unittest.rs, minidump-processor/src/stackwalker/arm_unittest.rs, minidump-processor/src/stackwalker/mips.rs, minidump-processor/src/stackwalker/mod.rs, minidump-processor/src/stackwalker/unwind.rs, minidump-processor/src/stackwalker/x86.rs, minidump-processor/src/stackwalker/x86_unittest.rs, minidump-stackwalk/src/main.rs, minidump/README.md, minidump/src/lib.rs, minidump/src/minidump.rs, minidump/tests/test_minidump.rs
...to abstract over memory streams and migrate all APIs to using them.
This makes rust-minidump work properly with modern "builtin" windows minidumps which only provide Memory64List. To see such a minidump: go to crash monitor, select an exe, right-click, "Create dump file". The resulting file will fail to stackwalk/analyze anything due to lack of memory.
This is an *enormous* breaking change to the primary `minidump` APIs, although minidump-processor's API I think works just as well. A second pass on docs might be worthwhile. Also it might be worthwhile to add an API to rust-minidump that handles fetching these streams for you.
Note that because I unconditionally only use the 64-bit stream over the 32-bit one if both exist, this will regress results if you specifically:
* Have both …
=> Introduce UnifiedMemoryList and UnifiedMemory 

RELEASES.md, minidump-common/src/format.rs
As far as I can tell, there was no reason for these structs to not implement `Pwrite`. This is needed for https://github.com/rust-minidump/minidump-writer/issues/8.
=> Make `minidump-common::format` structs writable through `scroll`.

minidump-processor/json-schema.md, minidump-processor/src/op_analysis.rs, minidump-processor/src/process_state.rs, minidump-processor/src/processor.rs, minidump-processor/tests/test_processor.rs, minidump-stackwalk/tests/snapshots/test_minidump_stackwalk__human-brief.snap, minidump-stackwalk/tests/snapshots/test_minidump_stackwalk__human-stable-all.snap, minidump-stackwalk/tests/snapshots/test_minidump_stackwalk__human-symbols.snap, minidump-stackwalk/tests/snapshots/test_minidump_stackwalk__human-unstable-all.snap, minidump-stackwalk/tests/snapshots/test_minidump_stackwalk__human.snap, minidump/src/context.rs, minidump/src/minidump.rs
values.
This includes (somewhat arbitrary) confidence values to help in determining the confidence of a bit flip.
Closes #808.
Starting as a draft because documentation needs to be updated.
=> Add additional details about the circumstances around possible bitflip

RELEASES.md, minidump/src/minidump.rs
When encountering a module with a bad image size, log a warning and continue instead of returning an error for the whole module list.
=> Skip modules with bad image sizes

Cargo.lock, minidump-synth/Cargo.toml, minidump-synth/src/lib.rs, minidump/Cargo.toml, minidump/src/minidump.rs
`encoding` is [unmaintained](https://rustsec.org/advisories/RUSTSEC-2021-0153.html), this PR just replaces its usage in `minidump` with `encoding_rs` and completely gets rid of it in `minidump-synth` in favor of just using `std::str::encode_utf16`
=> Replace `encoding` with `encoding_rs`

minidump-processor/json-schema.md, minidump-processor/src/op_analysis.rs, minidump-processor/src/process_state.rs, minidump-processor/src/processor.rs, minidump-processor/tests/test_processor.rs
This is useful for classifying exceptions (e.g., as buffer overflows).
=> Bug 1663983 - Check for memory accesses to likely guard pages.

minidump-unwind/src/symbols.rs
This PR fixes two bugs that prevented DebugInfoSymbolProvider from ever resolving an address to a function:
1. `partition_point` expects a closure that returns true at the head of the slice and false at the tail, but the closure originally provided did the opposite. This meant that `partition_point` always returned `0`, and `function_by_address` would therefore always return `None`.
2. `fill_symbol` was passing the raw instruction address into `function_by_address` rather than the debiased address required to resolve properly against the function addresses embedded in the binary.
As an example, here's before and after output of running minidump-stackwalk with `--use-local-debuginfo` on a minidump produced by the `diskwrite` example in the crash-handling repo: …
=> Start to fix DebugInfoSymbolProvider

minidump/src/minidump.rs
This change ignores warning about duplicate `UnusedStream` streams, as long as both streams are empty, as this is extremely common for dumps collected by WER.
=> don't warn on duplicate UnusedStream type streams

.github/workflows/release.yml, Cargo.toml, RELEASES.md, minidump-stackwalk/Cargo.toml
First commit is literally just me checking in the result of that command.
Second commit is me hand-editing the old hack I made to use the modern version cargo-dist understands (if you cut a prerelease it will use the contents of the "Unreleased" section without actually mutating RELEASES.md).
This drops support for arm64 linux, which was broken anyway.
=> setup cargo-dist

Cargo.lock, breakpad-symbols/fuzz/Cargo.lock, minidump-common/Cargo.toml, minidump-common/src/errors/linux.rs, minidump-common/src/errors/macos.rs, minidump-common/src/errors/windows.rs, minidump-common/src/format.rs, minidump-processor/fuzz/Cargo.lock, minidump-unwind/fuzz/Cargo.lock, minidump/fuzz/Cargo.lock
While the last release of num-derive is rather old, its repo has received recent updates, one of which is a bump to syn 2. It's also worth noting that num-derive is under the same umbrella org as num-traits, also used.
=> Switch to num-derive

minidump/src/minidump.rs
Expose the raw MINIDUMP_MEMORY_INFO field to access other fields such as allocation_base.
=> Expose raw MINIDUMP_MEMORY_INFO field.

minidump-common/src/format.rs
This will allow to use a bitflags 2-derived bitflags 1 implementation in mozilla-central.
=> Avoid relying on bitflags internals

Cargo.toml
Addresses the warning that shows up with rust 1.72.0:
```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```
=> add `resolver = "2"` to Cargo.toml

breakpad-symbols/src/http.rs, breakpad-symbols/src/lib.rs
When fetching a symbol file from an HTTP symbol supplier and the debug filename and debug identifier are missing, try looking up the debug information using the code info. If the lookup is successful, use that debug info to fetch the symbol file from the cache and symbol servers.
This uses a new feature in Mozilla Symbols Server where requesting a download with:
```
/<code_file>/<code_id>/<code_file>.sym
```
will return an HTTP 302 with the download API url using the debug file and debug id if the Mozilla Symbols Server has a record for that file.
Fixes #870
=> Lookup debug info using code info

minidump-processor/src/evil.rs, minidump-processor/src/processor.rs, minidump-stackwalk/tests/snapshots/test_minidump_stackwalk__json-pretty-evil-symbols.snap, testdata/evil.json
We've been writing thread names in all minidumps for a while, it's time to get rid of the old external annotation.
This closes issue #480.
=> Drop support the ThreadIdNameMapping annotation

breakpad-symbols/src/lib.rs
While writing my own fetcher for Symbol files, I wanted to make use of the `lookup` method. Sadly, although it returns `FileLookup` object, which is `pub`, the fields therein are not.
I think this is an oversight. All functions that use `FileLookup` also return the object, and all those functions are `pub`. Clearly these were meant to be used from outside this module, but as the fields are not marked as `pub`, they cannot.
I ended up copying all these functions inside my own crate; which works fine, but having this fixed in this create would be nice :)
=> Expose FileLookup fields

breakpad-symbols/src/http.rs
When the symbol supplier does a codeinfo lookup and it's successful, the symbol supplier gets back an HTTP 302 with a url to redirect to in the Location header. The path of that url may have additional parts at the beginning that should be ignored--the debug file and debug id are the third and second from the end.
This fixes the path part parsing so
individual_lookup_debug_info_by_code_info picks up the debug file and debug id correctly.
This fixes the code so it works with any of these symbols-url variations:
* `https://symbols.mozilla.org`
* `https://symbols.mozilla.org/`
* `https://symbols.mozilla.org/try`
* `https://symbols.mozilla.org/try/`
Fixes #882
=> Fix redirect url parsing (#882)

Cargo.lock, minidump/Cargo.toml, minidump/src/minidump.rs, minidump/tests/test_minidump.rs
There are a handful of tests (and thus functionality) regarding malformed input that we'd have to give up to merge this. This gives up support for parsing files with messed up whitespace and memory map lines that only have partial information (e.g. only the mapped addresses).
I don't think these two cases are important to support, however if we do want to support them I can make some changes to `procfs`.
I also ran into an odd case in the `backwards_range` test. As far as I can tell, the code in that test only incidentally failed because the old memory map parser was extremely permissive. The minidump used in that test has an empty or invalid `MinidumpLinuxMaps` stream (I think?), and the `MinidumpStream::read` call gets the entire minidump content as the stream `bytes`, which seems very …
=> Use the procfs crate in minidump for parsing linux memory maps.

Cargo.lock, minidump-processor/Cargo.toml, minidump-processor/tests/test_processor.rs, minidump/src/minidump.rs, minidump/tests/test_minidump.rs
The main problem is that the dependency on memmap2 then needs to be the exact same as the one the minidump crate has, which doesn't necessarily line up.
Another option would be to reexport Mmap.
=> Avoid requiring a dependency on memmap2 to use Minidump<'_, Mmap>

minidump-processor/src/processor.rs, minidump-unwind/README.md, minidump-unwind/fuzz/fuzz_targets/unwind.rs, minidump-unwind/src/amd64_unittest.rs, minidump-unwind/src/arm64_unittest.rs, minidump-unwind/src/arm_unittest.rs, minidump-unwind/src/lib.rs, minidump-unwind/src/x86_unittest.rs
the 'idx' fields on unwind_thread and unwind_frame (and those span names) are rust-minidump-private API used by minidump-debugger to do log filtering.
=> fix: restore the idx field on thread spans

Cargo.lock, README.md, minidump/Cargo.toml
`procfs-core` uses `chrono` as a default feature, this is unneeded, I only noticed it because `minidump-writer` already removed the dependency, but it was still present in the lockfile due to `minidump`.
Also fixes the CI badge that wasn't fixed when `master` was renamed to `main`.
=> Remove `chrono`

minidump-unwind/src/lib.rs, minidump/src/minidump.rs
Doing a little bit of profiling, I found that `UnifiedMemory::get_memory_at_address` is quite hot. This lead me to a comment that I added previously about doing overflow checks on every single access. Instead of doing that on every access, rather do it once ahead of using it within `walk_stack`.
=> Validate `stack_memory` once in `walk_stack`

minidump-common/src/format.rs, minidump/src/lib.rs, minidump/src/minidump.rs
Minimal implementation of the [MINIDUMP_THREAD_INFO_LIST ](https://learn.microsoft.com/en-us/windows/win32/api/minidumpapiset/ns-minidumpapiset-minidump_thread_info_list) stream per issue #324.
Tested with dumps containing the stream using `Minidump::read_path(path)` and `dump.get_stream::<MinidumpThreadInfoList>()` and confirmed correct parsing and access to the parsed data.
Let me know if you want further implementation before merging, and feel free to update.
=> Add support for the MINIDUMP_THREAD_INFO_LIST stream

minidump-unwind/src/symbols/mod.rs
I needed to pass a `SymbolProvider` trait object (`Box<dyn SymbolProvider>` in this case) to `walk_stack`. We could change `walk_stack` to take a `?Sized`, but there's a bunch of other functions that are parameterized on the same type. It was easier to just `impl` the trait for trait object references.
=> Impl `Symbol Provider` for `&dyn SymbolProvider`.

Cargo.lock, breakpad-symbols/src/lib.rs, minidump-unwind/Cargo.toml
Consumers can add more features to change object reading if desired.
The way the crate is written, at least one of `coff`/`elf`/`macho`/`pe`/`wasm`/`xcoff` must be enabled for `object::read::File` to be available. While we could limit the features even further and make consumers choose which formats to support, this instead assumes that they want to be able to read any of the formats since we need to choose at least one anyway.
=> Update framehop and change `object` to have minimal features.

Cargo.lock, minidump-unwind/Cargo.toml, minidump-unwind/src/symbols/debuginfo.rs
This removes one of the dependencies on `object 0.32`. The other (`backtrace`) will be removed in the next release (it has been updated in their main branch).
=> Update to wholesym 0.5.

Cargo.lock, minidump-unwind/Cargo.toml, minidump-unwind/src/symbols/debuginfo.rs
This removes the `thiserror` and `thiserror-no-std` dependencies. We also internalize the `object` `ModuleSectionInfo` impl for now as it'll be removed from `framehop` and `framehop` uses an incompatible version of `object` right now.
=> Update to framehop 0.12.2.

breakpad-symbols/src/sym_file/parser.rs
=> Fix symfiles containing newlines at the end of CFI sections failing to parse

Cargo.lock, minidump-unwind/Cargo.toml
Notably this still ends up with duplicated addr2line (and thus gimli) due to backtrace using a slightly older version.
=> Update a number of dependencies to remove some duplicates.

minidump-common/src/format.rs, minidump-unwind/src/symbols/debuginfo.rs
I have not tested this yet, but it should do the trick. I will test it out through `minidump-stackwalk`.
=> Add support for Fat MachO files in the minidump-unwind debuginfo symbol provider

minidump-processor/src/op_analysis.rs, minidump-processor/src/processor.rs
Resolves  #1031
Also renamed a few functions/variables to better distinguish between general protection fault and non-canonical crash.
=> Limit non-canonical inconsistency detection to selected opcodes

minidump-common/src/format.rs
This is a pretty simple change to allow Minidump-Writer to have the new soft error stream.
See: https://github.com/rust-minidump/minidump-writer/issues/31
=> Add soft error stream for minidump-writer #31

Cargo.lock, breakpad-symbols/src/lib.rs, minidump-unwind/Cargo.toml
Picking up a fix for https://github.com/mstange/samply/issues/341 that breaks the build when the zerocopy derive feature is enabled:
```
error[E0252]: the name `AsBytes` is defined multiple times
--> /Users/sfackler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/samply-symbols-0.23.0/src/breakpad/index.rs:15:23
|
14 | use zerocopy::{AsBytes, LittleEndian, Ref, U32, U64};
|                ------- previous import of the macro `AsBytes` here
15 | use zerocopy_derive::{AsBytes, FromBytes, FromZeroes, Unaligned};
|                       ^^^^^^^--
|                       |
|                       `AsBytes` reimported here
|                       help: remove unnecessary import
|
= note: `AsBytes` must be defined only once in the macro namespace of this module
```
=> Bump wholesym to 0.8

Cargo.toml, breakpad-symbols/Cargo.toml, minidump-common/Cargo.toml, minidump-processor/Cargo.toml, minidump-stackwalk/Cargo.toml, minidump-synth/Cargo.toml, minidump-unwind/Cargo.toml, minidump/Cargo.toml
Now that Cargo allows this, it seems better to just manage these settings in a single `Cargo.toml` file (especially the version!)
=> Use workspace settings for packages

minidump-unwind/src/amd64.rs, minidump-unwind/src/amd64_unittest.rs
Currently on `amd64` frame pointer resolution is not even attempted on Windows, because the `%rbp` can point into the 'middle' of the frame.
This does have a huge downside, if there are frame pointers, we're not even trying to consider them. This is especially bad for JIT code, where native frames may not have frame pointers but code emitted by the JIT could have them. It appears that this is what Unity does.
But instead of just not attempting it, we can do better. We still know that the given `%rbp` is guaranteed lower than the return address and given by [windows docs](https://docs.microsoft.com/en-us/cpp/build/exception-handling-x64) and e.g. the [goblin](https://github.com/m4b/goblin/blob/ac1fabdd2100bae949607a320fe5d8087c1e784a/src/pe/exception.rs#L560-L563) implementation.
```rs
// …
```
=> Implement frame pointer scan for windows

minidump-unwind/src/symbols/debuginfo.rs
When a success is returned, it causes stack scanning logic to go down this path:
https://github.com/rust-minidump/rust-minidump/blob/39485c0e61ba14af468d04e560518df6c123900c/minidump-unwind/src/lib.rs#L870
which requires the frame to have a symbol populated to proceed with stack scanning. Returning an error will allow stack scanning to proceed (which is more than likely desirable if you have symbols disabled).
=> Bug 1978423 - Return an error from fill_symbol when symbols are disabled

minidump/src/minidump.rs
We have a bunch of minidumps coming in now with an invalid linux maps section, which logs quite a few error, but minidump processing ignores the section just anyways: https://github.com/rust-minidump/rust-minidump/blob/39485c0e61ba14af468d04e560518df6c123900c/minidump-processor/src/processor.rs#L594
=> Downgrade linux maps log to warn
