rust-minidump/rust-minidump

minidump-processor/src/process_state.rs
minidump-processor/src/processor.rs
src/bin/minidump_dump.rs
src/context.rs
src/iostuff.rs
src/minidump.rs

The new style was used in a couple places; this change makes things more uniform.

use new-style `?` syntax instead of `try!`

---

.github/workflows/ci.yml
breakpad-symbols/src/lib.rs
breakpad-symbols/src/sym_file/mod.rs
breakpad-symbols/src/sym_file/parser.rs
breakpad-symbols/src/sym_file/types.rs
examples/dumpmodules.rs
minidump-common/src/format.rs
minidump-common/src/traits.rs
minidump-processor/src/bin/minidump_stackwalk.rs
minidump-processor/src/dwarf_symbolizer.rs
minidump-processor/src/lib.rs
minidump-processor/src/process_state.rs
minidump-processor/src/processor.rs
minidump-processor/src/stackwalker/mod.rs
minidump-processor/src/stackwalker/x86.rs
minidump-processor/src/stackwalker/x86_unittest.rs
minidump-processor/tests/test_processor.rs
minidump-tools/src/bin/dumpstack.rs
minidump-tools/src/bin/get-minidump-instructions.rs
minidump-tools/src/lib.rs
src/bin/minidump_dump.rs
src/context.rs
src/iostuff.rs
src/minidump.rs
src/synth_minidump.rs
src/system_info.rs
tests/test_minidump.rs

This adds some generic CI configuration and runs cargo-fmt on all the
code.  No code changes made.
For now still allow warnings, since there are a lot of them.

Run cargo fmt and add ci

---

src/minidump.rs

Fix integer overflow in location_slice

---

src/minidump.rs

While most of Crashpad's UTF8 strings are terminated with a NUL byte,
the string variant of annotation objects is not. The Breakpad parser for
CrashpadInfo ignores this, never validates the NUL byte, and doesn't
even implement parsing of annotation objects.
To make intentions more clear, this patch splits UTF8 string parsing
into two methods: one that validates the terminating NUL byte, and one
that does not.

Fix reading annotation object strings

---

minidump-processor/src/processor.rs
src/minidump.rs

Use the exception's thread id for requesting_thread as well

---

minidump-processor/src/processor.rs
minidump-processor/src/stackwalker/amd64.rs
minidump-processor/src/stackwalker/amd64_unittest.rs
minidump-processor/src/stackwalker/mod.rs
minidump-processor/src/stackwalker/unwind.rs
minidump-processor/src/stackwalker/x86.rs
minidump-processor/src/stackwalker/x86_unittest.rs
src/minidump.rs

fixes #164
This one is a bit hacky...

Handle null stack RVAs

---

Cargo.toml
minidump-common/Cargo.toml
minidump-common/src/format.rs
minidump-processor/src/process_state.rs
minidump-processor/src/processor.rs
minidump-processor/src/system_info.rs
src/context.rs
src/minidump.rs
src/system_info.rs

Also removes serde derive gunk I spidered throught the crate.

Make json output match mozilla's schema

---

minidump-processor/src/process_state.rs
minidump-processor/src/processor.rs
minidump/src/minidump.rs

[Based on this parser](https://github.com/mozilla-services/minidump-stackwalk/blob/db9c9d089834ca4275cbf554582e304d95f0a5df/minidump-stackwalk/stackwalker.cc#L1021-L1037)
Fixes #172

Implement Linux Standard Base support

---

minidump-common/src/format.rs
minidump/src/minidump.rs

Add support for macOS EXC_RESOURCE exceptions.

---

minidump-processor/src/processor.rs
minidump/src/bin/minidump_dump.rs
minidump/src/minidump.rs
minidump/src/synth_minidump.rs

It's dumped in mindump_dump, and parsed by minidump-processor (but not yet used).
Also did some gardening on MemoryStream since a lot of this code was copy pasted
and I wrote back any cleanups I made to the new code.
Fixes #21

Implement MemoryInfoStream

---

breakpad-symbols/src/lib.rs

this was DDOSing logging with like, gigabytes of logs

remove obscene debug line

---

minidump/src/minidump.rs
minidump/tests/test_minidump.rs

Wrong array was being passed in.
Fixes #270

Properly read csd_version

---

minidump-processor/src/process_state.rs
minidump-processor/src/processor.rs
minidump-processor/src/stackwalker/mod.rs
minidump/src/minidump.rs
minidump/src/system_info.rs

Implement last_error_value

---

minidump-processor/src/evil.rs
minidump-processor/src/lib.rs
minidump-processor/src/processor.rs
minidump-stackwalk/src/main.rs

Use the thread names in the evil json

---

Cargo.lock
RELEASES.md
breakpad-symbols/Cargo.toml
minidump-common/Cargo.toml
minidump-processor/Cargo.toml
minidump-stackwalk/Cargo.toml
minidump-tools/Cargo.toml
minidump/Cargo.toml
synth-minidump/Cargo.toml

See RELEASES.md for details!
(Already published)

0.9.2 release 

---

Cargo.lock
minidump-stackwalk/Cargo.toml

context: 
https://github.com/mozilla/dump_syms/blob/bf7f6bd855eb6ecb233b52bfa7b2c975b7026540/Cargo.toml#L40-L45
https://searchfox.org/mozilla-central/rev/6deb8b6af57a8b5b6b1bcb143ea498e566475d8d/taskcluster/scripts/misc/build-dump-syms.sh#52

add optional vendored-openssl feature

---

minidump-processor/src/stackwalker/arm.rs
minidump-processor/src/stackwalker/arm_unittest.rs

Be more strict about stack pointers on non-leaf ARM functions

---

Cargo.lock
README.md
RELEASES.md
breakpad-symbols/Cargo.toml
minidump-common/Cargo.toml
minidump-processor/Cargo.toml
minidump-stackwalk/Cargo.toml
minidump-stackwalk/README.md
minidump/Cargo.toml
synth-minidump/Cargo.toml

See RELEASES.md for details
(already published)

0.9.4 release

---

Cargo.lock
RELEASES.md
minidump-processor/src/process_state.rs
minidump-stackwalk/Cargo.toml
minidump-stackwalk/src/main.rs

See individual commits for details.

MISC minidump-stackwalk CLI work

---

minidump-processor/src/process_state.rs

Remove legacy truncation fields

---

minidump-processor/README.md
minidump-processor/json-schema.md
minidump-processor/src/process_state.rs
minidump-stackwalk/README.md
minidump-stackwalk/src/main.rs
minidump/src/system_info.rs

See rendered version here:
https://github.com/Gankra/rust-minidump/blob/schema/minidump-processor/json-schema.md

Add JSON Schema Document

---

RELEASES.md
minidump-stackwalk/src/main.rs

See https://docs.rs/clap/latest/clap/struct.Arg.html#method.multiple for details on why this was an issue

Fix multi named argument bug

---

minidump-processor/src/lib.rs
minidump-processor/src/stackwalker/mod.rs
minidump-processor/src/symbols.rs

Also repairs the symbolic shim so that it compiles again.

Document the Symbolizer interface and shim better

---

RELEASES.md
minidump-processor/json-schema.md
minidump-processor/src/process_state.rs

Json Schema Breaking Change: rename crashing_thread.thread_index to threads_index

---

Cargo.lock
RELEASES.md
breakpad-symbols/Cargo.toml
minidump-common/Cargo.toml
minidump-processor/Cargo.toml
minidump-stackwalk/Cargo.toml
minidump-stackwalk/README.md
minidump/Cargo.toml
synth-minidump/Cargo.toml

breaking changes to fix integration issues found during deployment.
More docs.
See RELEASES.md for details
(already published)

0.9.6 Release

---

minidump-stackwalk/src/main.rs

Start top-level errors with an error name.

---

breakpad-symbols/src/sym_file/parser.rs

Avoid overflow when getting symbol lines

---

minidump-processor/src/stackwalker/arm64.rs
minidump-processor/src/stackwalker/arm64_old.rs
minidump-processor/src/stackwalker/arm64_unittest.rs

Literally just a copy paste of https://github.com/luser/rust-minidump/pull/309
Fixes #428

Fix infinite loop when walking stack on ARM64

---

RELEASES.md

* There is now a "CURRENT BLOCKERS FOR THIS RELEASE" section to help us synchronize on what remains before cutting `0.10.0`
* Some high level notes on major work done
* Tried to include detailed notes as much as possible
In the future it would be appreciated if Sentry folks could add their own changes to this doc as part of the PR, but I understand if stuff slips through the cracks!

Add a ton of pending stuff to RELEASES.md

---

minidump-processor/src/stackwalker/arm.rs
minidump-processor/src/stackwalker/arm_unittest.rs

The LR register on ARM can be used as general purpose register, so we
should not expect it to hold a valid return addr. Except on iOS, which
has stricter calling conventions.
Based on top of #487, fixes #460.

fix: Restrict ARM32 LR unwinding to iOS 

---

breakpad-symbols/src/sym_file/walker.rs

This would fix #473. Compared to Breakpad's treatment of this case (see the linked issue), our check is more lax: they additionally check whether they're currently in a context frame, but we don't have this information in this function.

Windows X86: Fix pathological stackwalking case

---

Cargo.lock
Cargo.toml
RELEASES.md
breakpad-symbols/Cargo.toml
minidump-common/Cargo.toml
minidump-processor/Cargo.toml
minidump-processor/json-schema.md
minidump-stackwalk/Cargo.toml
minidump-stackwalk/README.md
minidump-stackwalk/tests/snapshots/test_minidump_stackwalk__long-help.snap
minidump-stackwalk/tests/snapshots/test_minidump_stackwalk__markdown-help.snap
minidump-stackwalk/tests/snapshots/test_minidump_stackwalk__short-help.snap
minidump/Cargo.toml
synth-minidump/Cargo.toml

See RELEASES.md for detailed release notes.

0.10.0 Release

---

minidump-common/src/format.rs

- Adds ContextFlagsArm, Arm64Old, and X86 according to their definitions in Breakpad.
- Derives Pwrite for CONTEXT_ARM, CONTEXT_ARM64_OLD and CONTEXT_X86
Note this conflicts with #501 so I can rebase after that is merged.

Flesh out non-x86_64 `CONTEXT_` structs

---

CONTRIBUTING.md
Cargo.lock
Cargo.toml
README.md
RELEASES.md
minidump-processor/Cargo.toml
minidump-processor/tests/test_processor.rs
minidump-stackwalk/Cargo.toml
minidump-stackwalk/tests/test-minidump-stackwalk.rs
minidump-synth/Cargo.toml
minidump-synth/README.md
minidump-synth/src/lib.rs
minidump/Cargo.toml
minidump/src/minidump.rs
synth-minidump/README.md

rename synth-minidump to minidump-synth to prepare for publish

---

RELEASES.md
minidump-stackwalk/src/main.rs
minidump/src/minidump.rs

Make MinidumpStream::STREAM_TYPE a u32

---

minidump-processor/src/stackwalker/arm64_old.rs

This applies the changes in https://github.com/rust-minidump/rust-minidump/pull/482 to the ARM64-old architecture.

Handle 0 frame pointers on ARM64-old

---

minidump-common/src/format.rs

These are various changes that I needed when implementing https://github.com/rust-minidump/minidump_writer_linux/pull/21

Add more derive impls

---

Cargo.lock
breakpad-symbols/Cargo.toml
breakpad-symbols/src/sym_file/parser.rs

This passes tests.
I haven't yet fed a full xul.sym to into it. This is probably a good opportunity to try out socc-pair.

Migrate to nom 7

---

minidump-processor/src/stackwalker/arm.rs
minidump-processor/src/stackwalker/arm64.rs
minidump-processor/src/stackwalker/arm64_old.rs
minidump-processor/src/stackwalker/arm64_unittest.rs
minidump-processor/src/stackwalker/arm_unittest.rs

fixes #605, maybe, still testing

strip more aggressively in arm64 cfi and fix fp/lr handling

---

minidump-common/src/format.rs

Small change that fixes https://github.com/rust-minidump/rust-minidump/issues/441
Just wanted to say the articles on this project were really fun and informative reads!

replace "matching debug info" link

---

minidump-common/src/errors/macos.rs
minidump/src/minidump.rs

* Fixed macOS ARM breakpoint and bad access exceptions
* Added missing macOS ARM bad access exceptions
* Added macOS ARM arithmetic exceptions
* Thoroughly added perma-links to Apple's sources to document the various types

Miscellaneous macOS exceptions improvements

---

minidump-processor/src/op_analysis.rs

Closes #749, refactoring a few things along the way.

Account for calls/jmps to non-canonical addresses.

---

minidump-stackwalk/src/main.rs

Since we are only dealing with files, this error will only result from stdio pipes closing, which we won't consider an error.
Closes #563.

Ignore `std::io::ErrorKind::BrokenPipe`.

---

minidump-processor/src/op_analysis.rs
minidump-processor/src/processor.rs

Support reading indirect call addresses and ret addresses from memory.

---

minidump-processor/src/processor.rs
minidump-processor/tests/test_processor.rs

32-bit platforms have much higher likelihood of false-positives due to larger portions of the address space being mapped.
Closes #810.

Only perform bit-flip detection on 64-bit platforms.

---

minidump-processor/src/processor.rs

After testing on a large data set, it seems like there are plenty of situations where there is a memory mapping that has no permissions. This puts a reasonable limit on the size of the mappings which are considered guard pages to avoid false positives.

Limit the size of mappings considered guard pages.

---

minidump-unwind/src/symbols.rs

Fix local debuginfo inline functions and line info

---

RELEASES.md
minidump-processor/json-schema.md

Update docs for cpu_microcode_version (#836)

---

Cargo.lock
breakpad-symbols/Cargo.toml
breakpad-symbols/src/http.rs
breakpad-symbols/src/lib.rs

Remove tokio to reduce the audit surface.

---

Cargo.lock
breakpad-symbols/fuzz/Cargo.lock
minidump-common/Cargo.toml
minidump-processor/fuzz/Cargo.lock
minidump-unwind/fuzz/Cargo.lock
minidump/fuzz/Cargo.lock

And refresh fuzzing Cargo.locks.

Update smart-default to 0.7

---

minidump-unwind/src/symbols.rs

The debug file may not be available, but even if it is, it doesn't contain unwind info.

Use the code file on win64 for unwind information.

---

minidump/src/minidump.rs

When interpreting Windows status code that have been stored as 64-bit values, ignore the upper 32 bits as they're likely to contain bogus data. In particular windbg.dll seems to sign-extend the 32-bit value when storing it as a 64-bit one.
Note that we're not really throwing away data with this patch as the status codes are supposed to be 32 bits, so we shouldn't have relied on the upper 32 bits being cleared in the first place.
This fixes issue #893

Interpret Windows error-code correctly even when they're sign-extended.

---

minidump-common/src/errors/macos.rs
minidump/src/minidump.rs

Add support for additional macOS guard exception types and flavors

---

minidump/src/minidump.rs

Print the si_code of a Linux signal correctly when it contains a negative code

---

breakpad-symbols/src/lib.rs
breakpad-symbols/src/sym_file/parser.rs
breakpad-symbols/src/sym_file/types.rs

Allow passing the path to a symbol files in --symbols-path

---

minidump-stackwalk/src/main.rs

Otherwise it is not required and the program shouldn't panic.
Closes #967.

Only require the MinidumpSystemInfo stream when using local debug info.

---

minidump-processor/src/processor.rs
minidump/src/minidump.rs

Resolves #1004 
Let me know if there's a better way to sort them.

Sort unknown and unimplemented streams for deterministic output

---

Cargo.lock
minidump-unwind/Cargo.toml

Update to wholesym 0.7.
